services:
  app:
    build: ./docker/php
    container_name: rb_app
    volumes:
      - ./:/var/www/html
    expose:
      - 9000
    user: "1000:1000"

  web:
    build: ./docker/nginx
    container_name: rb_web
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: rb_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql_data:
